platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'


target 'text' do
  pod 'MGJRouter', '~> 0.10.0'

 pod 'AFNetworking', '~> 3.2.1'
 pod 'MJRefresh', '~> 3.2.0'
  pod 'SDWebImage', '~> 5.0.6'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'ZFJFormKit', '~> 1.0.0'
  pod 'TTTAttributedLabel', '~> 2.0.0'

end